
name: Example Image Builder - Uvicorn

on: [push]

jobs:
  Uvicorn-Builder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        package_versions: ["0.12.1", "0.12.2", "0.12.3", "0.13.0", "0.13.1", "0.13.2", "0.13.3", "0.13.4", "0.14.0", "0.15.0"]
        target_base: ["full", "slim", "alpine"]
    steps:
      - name: "Create and push"
        uses: multi-py/action-python-image-builder@main
        with:
          package: "uvicorn"
          package_latest_version: "0.15.0"
          maintainer: "Myname <user@example.com>"
          python_version: ${{ matrix.python_version }}
          target_base: ${{ matrix.target_base }}
          package_version: ${{ matrix.package_versions }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
